import html2pdf from "html2pdf.js";
import { Internship } from "@/types";

export interface ExportOptions {
  filename?: string;
  margin?: number;
  fontSize?: number;
}

/**
 * Export comparison of internships as PDF
 */
export const exportComparisonAsPDF = (
  internships: Internship[],
  options: ExportOptions = {}
) => {
  const {
    filename = `internship-comparison-${
      new Date().toISOString().split("T")[0]
    }.pdf`,
    margin = 10,
    fontSize = 12,
  } = options;

  // Create HTML content for PDF
  const htmlContent = `
    <div style="font-family: Arial, sans-serif; padding: ${margin}mm; max-width: 210mm;">
      <h1 style="color: #333; text-align: center; margin-bottom: 30px;">
        Internship Comparison Report
      </h1>
      
      <p style="color: #666; text-align: center; margin-bottom: 20px; font-size: 12px;">
        Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}
      </p>

      ${internships
        .map(
          (internship, idx) => `
        <div style="page-break-inside: avoid; margin-bottom: 20px; border: 1px solid #ddd; padding: 15px; border-radius: 8px;">
          <h2 style="color: #222; margin: 0 0 10px 0; font-size: 18px;">
            ${idx + 1}. ${internship.title}
          </h2>
          
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 15px;">
            <div>
              <p style="margin: 5px 0; font-weight: bold; color: #555;">Company:</p>
              <p style="margin: 0; font-size: 14px;">${internship.company}</p>
            </div>
            
            <div>
              <p style="margin: 5px 0; font-weight: bold; color: #555;">Location:</p>
              <p style="margin: 0; font-size: 14px;">
                ${
                  typeof internship.location === "string"
                    ? internship.location
                    : internship.location?.city || "N/A"
                }
              </p>
            </div>

            <div>
              <p style="margin: 5px 0; font-weight: bold; color: #555;">Stipend:</p>
              <p style="margin: 0; font-size: 14px;">${internship.stipend}</p>
            </div>

            <div>
              <p style="margin: 5px 0; font-weight: bold; color: #555;">Duration:</p>
              <p style="margin: 0; font-size: 14px;">${internship.duration}</p>
            </div>

            <div>
              <p style="margin: 5px 0; font-weight: bold; color: #555;">Work Mode:</p>
              <p style="margin: 0; font-size: 14px;">${
                internship.work_mode || "N/A"
              }</p>
            </div>

            <div>
              <p style="margin: 5px 0; font-weight: bold; color: #555;">Deadline:</p>
              <p style="margin: 0; font-size: 14px;">${
                internship.deadline || "N/A"
              }</p>
            </div>
          </div>

          ${
            internship.sector_tags?.length > 0
              ? `
            <div>
              <p style="margin: 10px 0 5px 0; font-weight: bold; color: #555;">Sectors:</p>
              <p style="margin: 0; font-size: 12px;">
                ${internship.sector_tags.join(", ")}
              </p>
            </div>
          `
              : ""
          }

          ${
            internship.required_skills?.length > 0
              ? `
            <div>
              <p style="margin: 10px 0 5px 0; font-weight: bold; color: #555;">Required Skills:</p>
              <p style="margin: 0; font-size: 12px;">
                ${internship.required_skills.slice(0, 8).join(", ")}
                ${
                  internship.required_skills.length > 8
                    ? `, +${internship.required_skills.length - 8} more`
                    : ""
                }
              </p>
            </div>
          `
              : ""
          }

          ${
            internship.description
              ? `
            <div>
              <p style="margin: 10px 0 5px 0; font-weight: bold; color: #555;">Description:</p>
              <p style="margin: 0; font-size: 12px; line-height: 1.5;">
                ${internship.description.substring(0, 300)}${
                  internship.description.length > 300 ? "..." : ""
                }
              </p>
            </div>
          `
              : ""
          }
        </div>
      `
        )
        .join("")}

      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #999; font-size: 10px;">
        <p>Generated by Saksham AI - Internship Comparison Tool</p>
      </div>
    </div>
  `;

  const element = document.createElement("div");
  element.innerHTML = htmlContent;

  const opt = {
    margin: margin,
    filename: filename,
    image: { type: "jpeg" as const, quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: {
      orientation: "portrait" as const,
      unit: "mm" as const,
      format: "a4",
    },
  };

  html2pdf().set(opt).from(element).save();
};

/**
 * Export single internship as PDF
 */
export const exportInternshipAsPDF = (
  internship: Internship,
  options: ExportOptions = {}
) => {
  exportComparisonAsPDF([internship], {
    filename: `${internship.company}-${internship.title.replace(
      /\s+/g,
      "-"
    )}.pdf`,
    ...options,
  });
};
